### ISSUE TITLE
旋转一次后还原不了

### ISSUE THREAD

**Issue by Loren1994** [newbieYoung/Threejs_rubik#1]
只旋转一次,然后直接点击自动还原,还原不了

**Comment by newbieYoung** [comment]
@Loren1994 在移动端还是pc，手机型号、操作系统？重新刷新页面也有问题？页面里边有个查看日志输出的按钮，能点开反馈下里边的内容吗？

**Comment by Loren1994** [comment]
PC端,Safari, https://newbieyoung.github.io/Threejs_rubik/step5.html ,我试的是这个网页里的例子,你可以试一下,只旋转一次就点自动还原,我试的是每次都必现.
THREE.WebGLRenderer 82dev
start autoResetV1
start at:13499
start step1
start step2
start step3
start step4
something wrong in step4

**Comment by newbieYoung** [comment]
@Loren1994 收到我看下，谢谢反馈

**Comment by newbieYoung** [comment]
@Loren1994  应该是修复了......

**Comment by Loren1994** [comment]
不客气哈哈,现在好了👍
